sudo: required

language: csharp
cache:
  directories:
  - $PWD/packages

services:
  - docker

script:
  - docker build -t webapp:test .
  - docker run -it -v $PWD/packages:/root/.nuget/packages webapp:test